name: Build with Maven

on:
  push:
    branches: [ master, core-3.x ]
  pull_request:
    branches: [ master, core-3.x ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@main
    with:
      deploy_branch: '["master", "core-3.x"]'
    secrets:
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
      MAVEN_REPO_API_KEY: ${{ secrets.MAVEN_REPO_API_KEY }}

  owasp-dependency-check:
    if: ${{ github.event_name != 'pull_request' && github.ref_name != 'core-3.x' }}
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/owasp-dependency-check.yml@main
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      BOT_GH_TOKEN: ${{ secrets.OMRS_BOT_GH_TOKEN }}
